name: aisp-mission-board

services:
  app:
    image: fhsh/mission-board:latest
    build:
      dockerfile: app.Dockerfile
      context: .
    restart: always
    env_file:
      - env.d/app.env
    networks:
      - app
      - tunnel
    expose:
      - 8000 
    volumes:
      - ./app:/app # for development
      - ./data/logs:/temp/logs
  
  tw:
    image: fhsh/mission-board-tw:latest
    build:
      dockerfile: tw.Dockerfile
      context: .
    depends_on:
      - app
    volumes:
      - ./app/public/assets:/tw/dist
      - ./app/templates:/tw/templates
    command: ['pnpx', '@tailwindcss/cli', '-i', './src/input.css', '-o', './dist/style.css', '--optimize', '--watch=always'] # for development
    # command: pnpm build # for production
  
  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - env.d/mongo.env
    networks:
      - app
      - mngr
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
  
  me:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    env_file:
      - env.d/me.env
    networks:
      - mngr
      - tunnel
    expose:
      - 8081
  
  cf:
    image: cloudflare/cloudflared:latest
    restart: always
    env_file:
      - env.d/cf.env
    networks:
      - tunnel
    command: tunnel run

networks:
  app:
    internal: true
  mngr:
    internal: true
  tunnel: