name: aisp-mission-board

services:
  app:
    image: fhsh/mission-board:latest
    build:
      dockerfile: app.Dockerfile
      context: .
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - env.d/app.env
    networks:
      - app
      - tunnel
    expose:
      - 8000 
    volumes:
      - ./data/logs:/temp/logs
      - ./app/public/assets:/app/public/assets # for tailwindcss style.css
  
  tw:
    image: fhsh/mission-board-tw:latest
    build:
      dockerfile: tw.Dockerfile
      context: .
    depends_on:
      - app
    volumes:
      - ./app/public/assets:/tw/dist
      - ./app/templates:/tw/templates
    command: pnpm build # for production
  
  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - env.d/mongo.env
    networks:
      - app
      - mngr
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand(\"ping\").ok' --quiet"]
      interval: 20s      # 每 5 秒檢查一次
      timeout: 15s       # 逾時時間
      retries: 5       # 重試 10 次後才標記為 unhealthy
      start_period: 60s # 容器啟動後 60 秒才開始健康檢查
  
  me:
    image: mongo-express:latest
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - env.d/me.env
    networks:
      - mngr
      - tunnel
    expose:
      - 8081
  
  cf:
    image: cloudflare/cloudflared:latest
    restart: always
    env_file:
      - env.d/cf.env
    networks:
      - tunnel
    command: tunnel run

networks:
  app:
    internal: true
  mngr:
    internal: true
  tunnel: